# Site settings
title: Ming Y. Chow
email: mchow@cs.tufts.edu
description: > # this means to ignore newlines until "baseurl:"
  Ming Chow's website
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://mchow01.github.io" # the base hostname & protocol for your site
github_username: mchow01
linkedin_username: mchow01

# Build settings
markdown: kramdown
host: 0.0.0.0
